const axios = require('axios');
const fs = require('fs-extra');
const path = require('path');
const sharp = require('sharp');
const crypto = require('crypto');

const OUTPUT_DIR = path.join(__dirname, '../');

// Replace this with your actual GitHub username and repository later
const GITHUB_USER = 'Pro-Bandey'; 
const GITHUB_REPO = 'Onyx-IpTv';
const REMOTE_INDEX_URL = `https://raw.githubusercontent.com/${GITHUB_USER}/${GITHUB_REPO}/logos/logo-index.json`;

async function optimizeLogos() {
  await fs.ensureDir(OUTPUT_DIR);
  
  // 1. Load source targets generated by the DB script
  const logoSourcePath = path.join(__dirname, '../output-db/logo-source.json');
  if (!fs.existsSync(logoSourcePath)) {
    console.error('❌ logo-source.json not found! Run DB Builder first.');
    return;
  }
  const sources = await fs.readJson(logoSourcePath);

  // 2. Fetch existing Hash-State from the 'logos' branch to prevent re-processing
  let existingIndex = {};
  try {
    const { data } = await axios.get(REMOTE_INDEX_URL);
    existingIndex = data;
    console.log(`📦 Loaded existing index with ${Object.keys(existingIndex).length} logos.`);
  } catch (err) {
    console.log('⚠️ No existing remote index found. Starting fresh.');
  }

  const newIndex = { ...existingIndex };
  let processedCount = 0;

  for (const channel of sources) {
    if (!channel.url) continue;

    // Fast check: Have we processed this EXACT URL before?
    const urlHash = crypto.createHash('sha256').update(channel.url).digest('hex');
    
    if (existingIndex[channel.id] === urlHash) {
      // URL unchanged, skip completely.
      continue;
    }

    try {
      console.log(`🔄 Processing new logo for: ${channel.id}`);
      
      const response = await axios({
        url: channel.url,
        responseType: 'arraybuffer',
        timeout: 10000
      });

      const buffer = Buffer.from(response.data, 'binary');

      // Sharp Optimization Pipeline: WebP, Max 256x256, stripped metadata
      await sharp(buffer)
        .resize(256, 256, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
        .webp({ quality: 80, effort: 4 })
        .toFile(path.join(OUTPUT_DIR, `${channel.id}.webp`));

      // Update Hash-State
      newIndex[channel.id] = urlHash;
      processedCount++;

    } catch (err) {
      console.log(`❌ Failed to fetch/process ${channel.id}: ${err.message}`);
    }
  }

  // Save the new Hash-State index
  await fs.writeJson(path.join(OUTPUT_DIR, 'logo-index.json'), newIndex, { spaces: 2 });
  
  console.log(`✅ Logo Pipeline Complete. Optimized ${processedCount} new/changed logos.`);
}

optimizeLogos().catch(console.error);
