name: DB Builder Pipeline (Free IPTV Sync)

on:
  schedule:
    - cron: '0 0 * * 1,4'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run DB Generator Script
        run: npm run build:db

      - name: Deploy to db branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: db
          folder: db
          clean: true
          commit-message: "chore(db): sync and shard iptv database"